# Generated by Django 4.0.3 on 2022-07-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Num_Deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('middleInitial', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('oth_symptoms', models.CharField(max_length=200)),
                ('Num_OtherSymp', models.IntegerField()),
                ('Symptoms', models.CharField(max_length=200)),
                ('user_Info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfsys.userinfo')),
            ],
        ),
    ]
